import type { Lang } from './i18n';

export type Dict = Record<string, string>;

const es: Dict = {
  'nav.home': 'Inicio', 'nav.summary': 'Resumen', 'nav.calendar': 'Calendario', 'nav.community': 'Comunidad', 'nav.profile': 'Perfil', 'nav.settings': 'Ajustes', 'nav.record': 'Registrar',
  'dash.hello': '¡Hola', 'dash.today': 'Hoy', 'dash.weekPlan': 'Plan de la semana', 'dash.viewCalendar': 'Ver calendario', 'dash.regenerate': 'No me gusta, prepárame otra semana', 'dash.generating': 'Generando...', 'dash.regenDone': '¡Nuevo plan generado! Mira tu calendario.', 'dash.markDone': 'Marcar como hecho', 'dash.doneToday': '¡Completado hoy!', 'dash.gps': 'GPS', 'dash.recordActivity': 'Grabar actividad', 'dash.viewDetails': 'Ver detalles y consejos', 'dash.recoveryDay': 'Día de recuperación activa', 'dash.restDay': 'Descansa y recarga energías', 'dash.hydration': 'Hidratación', 'dash.glasses': 'vasos', 'dash.hydrationGoal': '¡Objetivo de hidratación alcanzado!', 'dash.yourGoal': 'Tu objetivo', 'dash.thisWeek': 'Esta semana', 'dash.days': 'días', 'dash.workouts': 'Entrenos', 'dash.weight': 'Peso', 'dash.progress': 'Progreso', 'dash.omsGoal': '¡Objetivo diario OMS alcanzado!', 'dash.minutes': 'min', 'dash.steps': 'Pasos', 'dash.calories': 'Calorías', 'dash.omsMinutes': 'Minutos OMS',
  'cal.title': 'Calendario', 'cal.weight': 'Peso', 'cal.weightEvolution': 'Evolución del peso', 'cal.noWeight': 'Sin registros de peso todavía.', 'cal.addFirst': 'Pulsa "Peso" para añadir tu primera medición.', 'cal.firstRecord': 'Primer registro. Añade más para ver la evolución.', 'cal.weeklyPlan': 'Plan semanal', 'cal.tapDetails': 'Toca para ver detalles o cambiar', 'cal.details': 'Detalles', 'cal.change': 'Cambiar', 'cal.cancel': 'Cancelar', 'cal.noWorkoutsDay': 'Sin entrenamientos este día.', 'cal.recentHistory': 'Historial reciente', 'cal.loading': 'Cargando...', 'cal.noWorkouts': 'Aún no has registrado entrenamientos.', 'cal.registerFirst': 'Registra tu primero desde la pestaña "Registrar".', 'cal.shared': 'Compartido', 'cal.public': 'Público', 'cal.private': 'Privado', 'cal.nutrition': 'Nutrición', 'cal.dailyCalories': 'Calorías diarias', 'cal.protein': 'Proteína', 'cal.carbs': 'Carbos', 'cal.fat': 'Grasas', 'cal.registerWeight': 'Registrar peso', 'cal.weightInKg': 'Peso en kg', 'cal.saveWeight': 'Guardar peso', 'cal.vagonetaMsg': '¿Más o menos, no quieres hacer nada vagueta? 😄',
  'sum.title': 'Resumen', 'sum.congrats': '¡Felicidades!', 'sum.weeklyProgress': 'Progreso semanal OMS', 'sum.today': 'Hoy', 'sum.strengthDays': 'Días de fuerza', 'sum.dailyGoal': 'Meta diaria', 'sum.recommended': 'Recomendado', 'sum.totalMinutes': 'Minutos totales', 'sum.km': 'Kilómetros', 'sum.elevation': 'Desnivel (m)', 'sum.workouts': 'Entrenamientos', 'sum.smartwatch': 'Sincronizar smartwatch', 'sum.connectWatch': 'Conecta tu reloj inteligente para volcar datos automáticamente', 'sum.connect': 'Conectar', 'sum.softRest': 'Marcar descanso suave', 'sum.softRestDesc': 'Registra un día de descanso activo sin presión', 'sum.achievements': 'Logros', 'sum.unlocked': 'Desbloqueado', 'sum.sleepQuestion': '¿Cómo has dormido?', 'sum.sleepAdjust': 'Ajustamos tu plan según tu descanso', 'sum.sleepGood': 'Bien', 'sum.sleepFair': 'Regular', 'sum.sleepPoor': 'Mal', 'sum.sleepSuggestion': 'Detectamos que no descansaste bien. Te sugerimos cambiar a un entreno más ligero hoy (recuperación activa o movilidad). Puedes mantener tu plan original si lo prefieres.', 'sum.badWeather': 'Clima adverso. ¡Anímate con ejercicio de interior hoy!', 'sum.goodWeather': 'Buen clima para entrenar al aire libre', 'sum.indoor': 'Interior', 'sum.omsWeekly': '¡Objetivo OMS semanal alcanzado!',
  'set.title': 'Ajustes', 'set.currentPlan': 'Plan actual', 'set.manageSub': 'Gestionar suscripción', 'set.sports': 'Deportes', 'set.edit': 'Editar', 'set.close': 'Cerrar', 'set.selectSports': 'Selecciona los deportes que practicas. Puedes añadir o quitar en cualquier momento.', 'set.addCustom': 'Añadir deporte personalizado...', 'set.saveSports': 'Guardar deportes', 'set.saved': 'Guardado', 'set.saving': 'Guardando...', 'set.weeklyPlan': 'Plan semanal', 'set.regenerateDesc': '¿No te gusta tu plan actual? Genera uno nuevo con tus deportes y objetivo.', 'set.notifications': 'Notificaciones', 'set.notifGeneral': 'Notificaciones generales', 'set.notifGeneralDesc': 'Activa o desactiva todas las notificaciones', 'set.notifFriends': 'Actividad de amigos', 'set.notifFriendsDesc': 'Avisos cuando tus amigos entrenan o te envían solicitudes', 'set.notifChallenges': 'Retos', 'set.notifChallengesDesc': 'Avisos sobre retos, rankings y plazos', 'set.notifAchievements': 'Logros', 'set.notifAchievementsDesc': 'Avisos cuando desbloqueas un nuevo logro o nivel', 'set.units': 'Unidades', 'set.weightUnit': 'Unidad de peso', 'set.kg': 'Kilogramos', 'set.lbs': 'Libras', 'set.language': 'Idioma', 'set.account': 'Tu cuenta', 'set.email': 'Email', 'set.name': 'Nombre',
  'prof.title': 'Perfil', 'prof.personalInfo': 'Información personal', 'prof.bodyStats': 'Datos corporales', 'prof.weight': 'Peso (kg)', 'prof.height': 'Altura (cm)', 'prof.age': 'Edad', 'prof.sex': 'Sexo', 'prof.male': 'Hombre', 'prof.female': 'Mujer', 'prof.memberSince': 'Miembro desde', 'prof.goal': 'Objetivo', 'prof.sports': 'Deportes', 'prof.nameUpdated': 'Nombre actualizado', 'prof.birthDate': 'Fecha de nacimiento', 'prof.happyBirthday': '¡Feliz cumpleaños!', 'prof.birthdayMsg': 'Hoy es tu cumpleaños. ¡Disfruta tu día especial y entrena con energía!',
  'ex.sessionGoal': 'Objetivo de la sesión', 'ex.tips': 'Consejos para el entrenamiento', 'ex.understood': 'Entendido', 'ex.duration': 'Duración', 'ex.calories': 'Calorías', 'ex.intensity': 'Intensidad', 'ex.low': 'Baja', 'ex.medium': 'Media', 'ex.high': 'Alta', 'ex.notFeeling': '¿No te gusta este ejercicio?', 'ex.changeExercise': 'Cambiar ejercicio', 'ex.changing': 'Cambiando...', 'ex.changed': '¡Ejercicio cambiado!',
  'mat.title': 'Materiales', 'mat.desc': 'Configura qué equipamiento tienes disponible para entrenar en casa. Adaptaremos las recomendaciones a tu material.', 'mat.gym': 'Voy al gimnasio (todo disponible)', 'mat.gymDesc': 'Si entrenas en gimnasio, no necesitas seleccionar materiales.', 'mat.home': 'Entreno en casa', 'mat.homeDesc': 'Selecciona el material que tienes disponible en casa.', 'mat.save': 'Guardar materiales', 'mat.saved': 'Materiales guardados', 'mat.saving': 'Guardando...', 'mat.dumbbells': 'Mancuernas', 'mat.barbell': 'Barra y discos', 'mat.kettlebell': 'Pesa rusa (Kettlebell)', 'mat.bands': 'Bandas elásticas', 'mat.pullup': 'Barra de dominadas', 'mat.bench': 'Banco', 'mat.mat': 'Esterilla', 'mat.bodyweight': 'Solo peso corporal',
  'common.cancel': 'Cancelar', 'common.save': 'Guardar',
  'goal.lose_weight': 'Perder peso', 'goal.gain_muscle': 'Musculación', 'goal.general_health': 'Hacer deporte por salud', 'goal.define': 'Definir', 'goal.gain_strength': 'Ganar fuerza',
  'set.changeGoal': 'Cambiar objetivo', 'set.changeGoalDesc': 'Cambia tu meta principal. Se adaptarán tu plan y recomendaciones.', 'set.goalChanged': '¡Objetivo actualizado! Tu plan se ha regenerado.',
  'health.title': 'Conexión con apps de salud', 'health.desc': 'Conecta con la plataforma de salud de tu dispositivo para sincronizar automáticamente tus pasos diarios.', 'health.connect': 'Conectar', 'health.disconnect': 'Desconectar', 'health.connected': 'Conectado', 'health.disconnected': 'No conectado', 'health.connecting': 'Conectando...', 'health.selectProvider': 'Selecciona tu plataforma de salud', 'health.appleHealth': 'Apple Health', 'health.googleFit': 'Google Fit', 'health.healthConnect': 'Health Connect', 'health.samsungHealth': 'Samsung Health', 'health.huaweiHealth': 'Huawei Salud', 'health.permissionTitle': 'Permisos de salud', 'health.permissionDesc': 'Necesitamos permiso para leer tus pasos diarios desde la plataforma de salud de tu dispositivo.', 'health.requestPermission': 'Solicitar permiso', 'health.grant': 'Conceder acceso', 'health.infoNote': 'Nota: Al conectar, solo se sincronizarán y subirán automáticamente los pasos diarios. Los pasos importados no contarán como una sesión de entrenamiento completada (no se computarán como 45 minutos de actividad planificada).', 'health.synced': 'Pasos sincronizados correctamente', 'health.syncError': 'Error al sincronizar pasos', 'health.todaySteps': 'Pasos de hoy', 'health.lastSync': 'Última sincronización', 'health.connectedProvider': 'Plataforma conectada',
  'cal.delete': 'Eliminar', 'cal.confirmDelete': 'Eliminar entrenamiento', 'cal.confirmDeleteMsg': '¿Seguro que quieres eliminar este entrenamiento? Esta acción no se puede deshacer.', 'cal.deleted': 'Entrenamiento eliminado', 'cal.deleting': 'Eliminando...', 'cal.viewRoute': 'Ver ruta',
  'gps.summary': 'Resumen de la ruta', 'gps.avgSpeed': 'Velocidad media', 'gps.maxSpeed': 'Velocidad máxima', 'gps.elevation': 'Desnivel', 'gps.cadence': 'Cadencia', 'gps.power': 'Potencia estimada', 'gps.pace': 'Ritmo medio', 'gps.pacePerKm': 'min/km', 'gps.lapTime': 'Tiempo por vuelta', 'gps.stepCadence': 'Cadencia de pasos', 'gps.distance': 'Distancia', 'gps.duration': 'Duración', 'gps.calories': 'Calorías', 'gps.steps': 'Pasos', 'gps.cyclingMetrics': 'Métricas de ciclismo', 'gps.runningMetrics': 'Métricas de carrera', 'gps.routeSummary': 'Resumen de la actividad', 'gps.finishActivity': 'Finalizar actividad', 'gps.cyclingSummary': 'Resumen de ciclismo', 'gps.runningSummary': 'Resumen de carrera', 'gps.walkingSummary': 'Resumen de marcha', 'gps.sportSummary': 'Resumen de la actividad',

};

const eu: Dict = {
  'nav.home': 'Hasiera', 'nav.summary': 'Laburpena', 'nav.calendar': 'Egutegia', 'nav.community': 'Komunitatea', 'nav.profile': 'Profila', 'nav.settings': 'Ezarpenak', 'nav.record': 'Erregistratu',
  'dash.hello': 'Kaixo', 'dash.today': 'Gaur', 'dash.weekPlan': 'Asteko plana', 'dash.viewCalendar': 'Egutegia ikusi', 'dash.regenerate': 'Ez dut gustuko, prestatu beste aste bat', 'dash.generating': 'Sortzen...', 'dash.regenDone': 'Plan berria sortuta! Begiratu zure egutegia.', 'dash.markDone': 'Eginda markatu', 'dash.doneToday': 'Gaur eginda!', 'dash.gps': 'GPS', 'dash.recordActivity': 'Jarduera grabatu', 'dash.viewDetails': 'Xehetasunak eta aholkuak ikusi', 'dash.recoveryDay': 'Berreskuratze aktiboaren eguna', 'dash.restDay': 'Atseden hartu eta indarra berreskuratu', 'dash.hydration': 'Hidratazioa', 'dash.glasses': 'edalontzi', 'dash.hydrationGoal': 'Hidratazio helburua lortuta!', 'dash.yourGoal': 'Zure helburua', 'dash.thisWeek': 'Aste honetan', 'dash.days': 'egun', 'dash.workouts': 'Entrenuak', 'dash.weight': 'Pisua', 'dash.progress': 'Aurrerapena', 'dash.omsGoal': 'EGMko eguneroko helburua lortuta!', 'dash.minutes': 'min', 'dash.steps': 'Urratsak', 'dash.calories': 'Kaloriak', 'dash.omsMinutes': 'EGM minutuak',
  'cal.title': 'Egutegia', 'cal.weight': 'Pisua', 'cal.weightEvolution': 'Pisuaren bilakaera', 'cal.noWeight': 'Ez dago pisu erregistrorik oraindik.', 'cal.addFirst': 'Sakatu "Pisua" zure lehen neurria gehitzeko.', 'cal.firstRecord': 'Lehen erregistroa. Gehitu gehiago bilakaera ikusteko.', 'cal.weeklyPlan': 'Asteko plana', 'cal.tapDetails': 'Sakatu xehetasunak ikusteko edo aldatzeko', 'cal.details': 'Xehetasunak', 'cal.change': 'Aldatu', 'cal.cancel': 'Utzi', 'cal.noWorkoutsDay': 'Entrenamendurik ez egun honetan.', 'cal.recentHistory': 'Azken historia', 'cal.loading': 'Kargatzen...', 'cal.noWorkouts': 'Ez duzu entrenamendurik erregistratu oraindik.', 'cal.registerFirst': 'Erregistratu zure lehena "Erregistratu" fitxatik.', 'cal.shared': 'Partekatuta', 'cal.public': 'Publikoa', 'cal.private': 'Pribatua', 'cal.nutrition': 'Nutrizioa', 'cal.dailyCalories': 'Eguneroko kaloriak', 'cal.protein': 'Proteina', 'cal.carbs': 'Karbohidratoak', 'cal.fat': 'Gantzak', 'cal.registerWeight': 'Pisua erregistratu', 'cal.weightInKg': 'Pisua kg-tan', 'cal.saveWeight': 'Pisua gorde', 'cal.vagonetaMsg': 'Dago-dago, ez duzu ezer egin nahi alferrik? 😄',
  'sum.title': 'Laburpena', 'sum.congrats': 'Zorionak!', 'sum.weeklyProgress': 'EGMko asteko aurrerapena', 'sum.today': 'Gaur', 'sum.strengthDays': 'Indar egunak', 'sum.dailyGoal': 'Eguneroko helburua', 'sum.recommended': 'Gomendatuta', 'sum.totalMinutes': 'Minutu totalak', 'sum.km': 'Kilometroak', 'sum.elevation': 'Desnibela (m)', 'sum.workouts': 'Entrenamenduak', 'sum.smartwatch': 'Smartwatch-a sinkronizatu', 'sum.connectWatch': 'Konektatu zure erloju adimentsua datuak automatikoki igortzeko', 'sum.connect': 'Konektatu', 'sum.softRest': 'Atseden biguna markatu', 'sum.softRestDesc': 'Erregistratu presiorik gabeko atseden egun bat', 'sum.achievements': 'Lorpenak', 'sum.unlocked': 'Desblokeatuta', 'sum.sleepQuestion': 'Nola lo egin duzu?', 'sum.sleepAdjust': 'Zure atsedenaren arabera plana doitzen dugu', 'sum.sleepGood': 'Ondo', 'sum.sleepFair': 'Erdizka', 'sum.sleepPoor': 'Gaizki', 'sum.sleepSuggestion': 'Ez duzu ondo atseden hartu detektatu dugu. Entrenamendu arinago batera aldatzea gomendatzen dizugu gaur (berreskuratze aktiboa edo mugikortasuna). Zure jatorrizko plana mantendu dezakezu nahi baduzu.', 'sum.badWeather': 'Eguraldi txarra. Animatu barruko ariketarekin gaur!', 'sum.goodWeather': 'Eguraldi ona kanpoan entrenatzeko', 'sum.indoor': 'Barrukoa', 'sum.omsWeekly': 'EGMko asteko helburua lortuta!',
  'set.title': 'Ezarpenak', 'set.currentPlan': 'Uneko plana', 'set.manageSub': 'Harpidetza kudeatu', 'set.sports': 'Kirolak', 'set.edit': 'Editatu', 'set.close': 'Itxi', 'set.selectSports': 'Hautatu praktikatzen dituzun kirolak. Edonoiz gehitu edo kendu ditzakezu.', 'set.addCustom': 'Kirol pertsonalizatua gehitu...', 'set.saveSports': 'Kirolak gorde', 'set.saved': 'Gordeta', 'set.saving': 'Gordetzen...', 'set.weeklyPlan': 'Asteko plana', 'set.regenerateDesc': 'Ez duzu zure uneko plana gustuko? Sortu berri bat zure kirolekin eta helburuarekin.', 'set.notifications': 'Jakinarazpenak', 'set.notifGeneral': 'Jakinarazpen orokorrak', 'set.notifGeneralDesc': 'Aktibatu edo desaktibatu jakinarazpen guztiak', 'set.notifFriends': 'Lagunen jarduera', 'set.notifFriendsDesc': 'Abisuak zure lagunak entrenatzen direnean edo eskaerak bidaltzean', 'set.notifChallenges': 'Erronkak', 'set.notifChallengesDesc': 'Abisuak erronkei, sailkapenei eta epeei buruz', 'set.notifAchievements': 'Lorpenak', 'set.notifAchievementsDesc': 'Abisuak lorpen edo maila berria desblokeatzean', 'set.units': 'Unitateak', 'set.weightUnit': 'Pisu unitatea', 'set.kg': 'Kilogramoak', 'set.lbs': 'Librak', 'set.language': 'Hizkuntza', 'set.account': 'Zure kontua', 'set.email': 'Emaila', 'set.name': 'Izena',
  'prof.title': 'Profila', 'prof.personalInfo': 'Informazio pertsonala', 'prof.bodyStats': 'Gorputz-datuak', 'prof.weight': 'Pisua (kg)', 'prof.height': 'Altuera (cm)', 'prof.age': 'Adina', 'prof.sex': 'Sexua', 'prof.male': 'Gizonezkoa', 'prof.female': 'Emakumezkoa', 'prof.memberSince': 'Kidea denetik', 'prof.goal': 'Helburua', 'prof.sports': 'Kirolak', 'prof.nameUpdated': 'Izena eguneratuta', 'prof.birthDate': 'Jaiotza-data', 'prof.happyBirthday': 'Zorionak zure urtebetetzean!', 'prof.birthdayMsg': 'Gaur zure urtebetetzea da. Gozatu zure egun berezia eta entrenatu energiaz!',
  'ex.sessionGoal': 'Saioko helburua', 'ex.tips': 'Entrenamendurako aholkuak', 'ex.understood': 'Ulertuta', 'ex.duration': 'Iraupena', 'ex.calories': 'Kaloriak', 'ex.intensity': 'Intentsitatea', 'ex.low': 'Baxua', 'ex.medium': 'Erdikoa', 'ex.high': 'Altua', 'ex.notFeeling': 'Ez duzu ariketa hau gustuko?', 'ex.changeExercise': 'Ariketa aldatu', 'ex.changing': 'Aldatzen...', 'ex.changed': 'Ariketa aldatuta!',
  'mat.title': 'Materialak', 'mat.desc': 'Konfiguratu etxean entrenatzeko duzun ekipoa. Gomendazioak zure materialera egokituko ditugu.', 'mat.gym': 'Gimnasiora noa (dena erabilgarri)', 'mat.gymDesc': 'Gimnasioan entrenatzen baduzu, ez duzu materialik hautatu behar.', 'mat.home': 'Etxean entrenatu', 'mat.homeDesc': 'Hautatu etxean duzun material erabilgarria.', 'mat.save': 'Materialak gorde', 'mat.saved': 'Materialak gordeta', 'mat.saving': 'Gordetzen...', 'mat.dumbbells': 'Esku-pesuak', 'mat.barbell': 'Barra eta diskoak', 'mat.kettlebell': 'Kettlebell', 'mat.bands': 'Bandera elastikoak', 'mat.pullup': 'Dominaden barra', 'mat.bench': 'Bankua', 'mat.mat': 'Alfonbra', 'mat.bodyweight': 'Gorputz-pisua soilik',
  'common.cancel': 'Utzi', 'common.save': 'Gorde',
  'goal.lose_weight': 'Pisua galdu', 'goal.gain_muscle': 'Muskulazioa', 'goal.general_health': 'Kirola egin osasunagatik', 'goal.define': 'Definitu', 'goal.gain_strength': 'Indarra irabazi',
  'set.changeGoal': 'Helburua aldatu', 'set.changeGoalDesc': 'Aldatu zure helburu nagusia. Zure plana eta gomendioak egokituko dira.', 'set.goalChanged': 'Helburua eguneratuta! Zure plana berriz sortu da.',
  'health.title': 'Osasun-aplikazioen konexioa', 'health.desc': 'Konektatu zure gailuaren osasun-plataformarekin zure eguneroko urratsak automatikoki sinkronizatzeko.', 'health.connect': 'Konektatu', 'health.disconnect': 'Deskonektatu', 'health.connected': 'Konektatuta', 'health.disconnected': 'Konektatu gabe', 'health.connecting': 'Konektatzen...', 'health.selectProvider': 'Hautatu zure osasun-plataforma', 'health.appleHealth': 'Apple Health', 'health.googleFit': 'Google Fit', 'health.healthConnect': 'Health Connect', 'health.samsungHealth': 'Samsung Health', 'health.huaweiHealth': 'Huawei Salud', 'health.permissionTitle': 'Osasun-baimenak', 'health.permissionDesc': 'Zure gailuaren osasun-plataformatik eguneroko urratsak irakurtzeko baimena behar dugu.', 'health.requestPermission': 'Baimena eskatu', 'health.grant': 'Sarbidea eman', 'health.infoNote': 'Oharra: Konektatzean, eguneroko urratsak soilik sinkronizatuko eta automatikoki igoko dira. Inportatutako urratsak ez dira entrenamendu-saio bat bezala kontabilizatuko (ez dira 45 minutuko planifikatutako jarduera bezala zenbatuko).', 'health.synced': 'Urratsak ondo sinkronizatuta', 'health.syncError': 'Errorea urratsak sinkronizatzean', 'health.todaySteps': 'Gaurko urratsak', 'health.lastSync': 'Azken sinkronizazioa', 'health.connectedProvider': 'Konektatutako plataforma',
  'cal.delete': 'Ezabatu', 'cal.confirmDelete': 'Entrenamendua ezabatu', 'cal.confirmDeleteMsg': 'Ziur entrenamendu hau ezabatu nahi duzula? Ekintza hau ezin da desegin.', 'cal.deleted': 'Entrenamendua ezabatuta', 'cal.deleting': 'Ezabatzen...', 'cal.viewRoute': 'Ibilbidea ikusi',
  'gps.summary': 'Ibilbidearen laburpena', 'gps.avgSpeed': 'Batez besteko abiadura', 'gps.maxSpeed': 'Gehienezko abiadura', 'gps.elevation': 'Desnibela', 'gps.cadence': 'Kadentzia', 'gps.power': 'Estimatutako potentzia', 'gps.pace': 'Batez besteko erritmoa', 'gps.pacePerKm': 'min/km', 'gps.lapTime': 'Itzuliko denbora', 'gps.stepCadence': 'Urrats-kadentzia', 'gps.distance': 'Distantzia', 'gps.duration': 'Iraupena', 'gps.calories': 'Kaloriak', 'gps.steps': 'Urratsak', 'gps.cyclingMetrics': 'Txirrindularitza-metrika', 'gps.runningMetrics': 'Korrika-metrika', 'gps.routeSummary': 'Jardueraren laburpena', 'gps.finishActivity': 'Jarduera amaitu', 'gps.cyclingSummary': 'Txirrindularitzaren laburpena', 'gps.runningSummary': 'Korrikaren laburpena', 'gps.walkingSummary': 'Martxaren laburpena', 'gps.sportSummary': 'Jardueraren laburpena',

};

const en: Dict = {
  'nav.home': 'Home', 'nav.summary': 'Summary', 'nav.calendar': 'Calendar', 'nav.community': 'Community', 'nav.profile': 'Profile', 'nav.settings': 'Settings', 'nav.record': 'Record',
  'dash.hello': 'Hello', 'dash.today': 'Today', 'dash.weekPlan': 'Weekly plan', 'dash.viewCalendar': 'View calendar', 'dash.regenerate': "I don't like it, prepare another week", 'dash.generating': 'Generating...', 'dash.regenDone': 'New plan generated! Check your calendar.', 'dash.markDone': 'Mark as done', 'dash.doneToday': 'Completed today!', 'dash.gps': 'GPS', 'dash.recordActivity': 'Record activity', 'dash.viewDetails': 'View details and tips', 'dash.recoveryDay': 'Active recovery day', 'dash.restDay': 'Rest and recharge', 'dash.hydration': 'Hydration', 'dash.glasses': 'glasses', 'dash.hydrationGoal': 'Hydration goal reached!', 'dash.yourGoal': 'Your goal', 'dash.thisWeek': 'This week', 'dash.days': 'days', 'dash.workouts': 'Workouts', 'dash.weight': 'Weight', 'dash.progress': 'Progress', 'dash.omsGoal': 'Daily WHO goal reached!', 'dash.minutes': 'min', 'dash.steps': 'Steps', 'dash.calories': 'Calories', 'dash.omsMinutes': 'WHO minutes',
  'cal.title': 'Calendar', 'cal.weight': 'Weight', 'cal.weightEvolution': 'Weight evolution', 'cal.noWeight': 'No weight records yet.', 'cal.addFirst': 'Tap "Weight" to add your first measurement.', 'cal.firstRecord': 'First record. Add more to see the evolution.', 'cal.weeklyPlan': 'Weekly plan', 'cal.tapDetails': 'Tap to view details or change', 'cal.details': 'Details', 'cal.change': 'Change', 'cal.cancel': 'Cancel', 'cal.noWorkoutsDay': 'No workouts this day.', 'cal.recentHistory': 'Recent history', 'cal.loading': 'Loading...', 'cal.noWorkouts': "You haven't recorded any workouts yet.", 'cal.registerFirst': 'Record your first one from the "Record" tab.', 'cal.shared': 'Shared', 'cal.public': 'Public', 'cal.private': 'Private', 'cal.nutrition': 'Nutrition', 'cal.dailyCalories': 'Daily calories', 'cal.protein': 'Protein', 'cal.carbs': 'Carbs', 'cal.fat': 'Fat', 'cal.registerWeight': 'Log weight', 'cal.weightInKg': 'Weight in kg', 'cal.saveWeight': 'Save weight', 'cal.vagonetaMsg': "Come on, you don't want to do anything lazy? 😄",
  'sum.title': 'Summary', 'sum.congrats': 'Congratulations!', 'sum.weeklyProgress': 'Weekly WHO progress', 'sum.today': 'Today', 'sum.strengthDays': 'Strength days', 'sum.dailyGoal': 'Daily goal', 'sum.recommended': 'Recommended', 'sum.totalMinutes': 'Total minutes', 'sum.km': 'Kilometers', 'sum.elevation': 'Elevation (m)', 'sum.workouts': 'Workouts', 'sum.smartwatch': 'Sync smartwatch', 'sum.connectWatch': 'Connect your smartwatch to automatically sync data', 'sum.connect': 'Connect', 'sum.softRest': 'Mark soft rest', 'sum.softRestDesc': 'Record an active rest day with no pressure', 'sum.achievements': 'Achievements', 'sum.unlocked': 'Unlocked', 'sum.sleepQuestion': 'How did you sleep?', 'sum.sleepAdjust': 'We adjust your plan based on your rest', 'sum.sleepGood': 'Good', 'sum.sleepFair': 'Fair', 'sum.sleepPoor': 'Poor', 'sum.sleepSuggestion': "We noticed you didn't rest well. We suggest switching to a lighter workout today (active recovery or mobility). You can keep your original plan if you prefer.", 'sum.badWeather': 'Bad weather. Try indoor exercise today!', 'sum.goodWeather': 'Good weather for outdoor training', 'sum.indoor': 'Indoor', 'sum.omsWeekly': 'Weekly WHO goal reached!',
  'set.title': 'Settings', 'set.currentPlan': 'Current plan', 'set.manageSub': 'Manage subscription', 'set.sports': 'Sports', 'set.edit': 'Edit', 'set.close': 'Close', 'set.selectSports': 'Select the sports you practice. You can add or remove anytime.', 'set.addCustom': 'Add custom sport...', 'set.saveSports': 'Save sports', 'set.saved': 'Saved', 'set.saving': 'Saving...', 'set.weeklyPlan': 'Weekly plan', 'set.regenerateDesc': "Don't like your current plan? Generate a new one with your sports and goal.", 'set.notifications': 'Notifications', 'set.notifGeneral': 'General notifications', 'set.notifGeneralDesc': 'Enable or disable all notifications', 'set.notifFriends': 'Friends activity', 'set.notifFriendsDesc': 'Alerts when your friends train or send requests', 'set.notifChallenges': 'Challenges', 'set.notifChallengesDesc': 'Alerts about challenges, rankings and deadlines', 'set.notifAchievements': 'Achievements', 'set.notifAchievementsDesc': 'Alerts when you unlock a new achievement or level', 'set.units': 'Units', 'set.weightUnit': 'Weight unit', 'set.kg': 'Kilograms', 'set.lbs': 'Pounds', 'set.language': 'Language', 'set.account': 'Your account', 'set.email': 'Email', 'set.name': 'Name',
  'prof.title': 'Profile', 'prof.personalInfo': 'Personal info', 'prof.bodyStats': 'Body stats', 'prof.weight': 'Weight (kg)', 'prof.height': 'Height (cm)', 'prof.age': 'Age', 'prof.sex': 'Sex', 'prof.male': 'Male', 'prof.female': 'Female', 'prof.memberSince': 'Member since', 'prof.goal': 'Goal', 'prof.sports': 'Sports', 'prof.nameUpdated': 'Name updated', 'prof.birthDate': 'Date of birth', 'prof.happyBirthday': 'Happy Birthday!', 'prof.birthdayMsg': 'Today is your birthday. Enjoy your special day and train with energy!',
  'ex.sessionGoal': 'Session goal', 'ex.tips': 'Training tips', 'ex.understood': 'Got it', 'ex.duration': 'Duration', 'ex.calories': 'Calories', 'ex.intensity': 'Intensity', 'ex.low': 'Low', 'ex.medium': 'Medium', 'ex.high': 'High', 'ex.notFeeling': "Don't like this exercise?", 'ex.changeExercise': 'Change exercise', 'ex.changing': 'Changing...', 'ex.changed': 'Exercise changed!',
  'mat.title': 'Equipment', 'mat.desc': 'Configure what equipment you have for home workouts. We will adapt recommendations to your gear.', 'mat.gym': 'I go to the gym (all available)', 'mat.gymDesc': 'If you train at a gym, you do not need to select equipment.', 'mat.home': 'Home workout', 'mat.homeDesc': 'Select the equipment you have at home.', 'mat.save': 'Save equipment', 'mat.saved': 'Equipment saved', 'mat.saving': 'Saving...', 'mat.dumbbells': 'Dumbbells', 'mat.barbell': 'Barbell and plates', 'mat.kettlebell': 'Kettlebell', 'mat.bands': 'Resistance bands', 'mat.pullup': 'Pull-up bar', 'mat.bench': 'Bench', 'mat.mat': 'Mat', 'mat.bodyweight': 'Bodyweight only',
  'common.cancel': 'Cancel', 'common.save': 'Save',
  'goal.lose_weight': 'Lose weight', 'goal.gain_muscle': 'Build muscle', 'goal.general_health': 'Exercise for health', 'goal.define': 'Define', 'goal.gain_strength': 'Gain strength',
  'set.changeGoal': 'Change goal', 'set.changeGoalDesc': 'Change your main goal. Your plan and recommendations will adapt.', 'set.goalChanged': 'Goal updated! Your plan has been regenerated.',
  'health.title': 'Health app connection', 'health.desc': 'Connect with your device health platform to automatically sync your daily steps.', 'health.connect': 'Connect', 'health.disconnect': 'Disconnect', 'health.connected': 'Connected', 'health.disconnected': 'Not connected', 'health.connecting': 'Connecting...', 'health.selectProvider': 'Select your health platform', 'health.appleHealth': 'Apple Health', 'health.googleFit': 'Google Fit', 'health.healthConnect': 'Health Connect', 'health.samsungHealth': 'Samsung Health', 'health.huaweiHealth': 'Huawei Health', 'health.permissionTitle': 'Health permissions', 'health.permissionDesc': 'We need permission to read your daily steps from your device health platform.', 'health.requestPermission': 'Request permission', 'health.grant': 'Grant access', 'health.infoNote': 'Note: When connected, only daily steps will be synced and uploaded automatically. Imported steps will not count as a completed workout session (they will not be counted as 45 minutes of planned activity).', 'health.synced': 'Steps synced successfully', 'health.syncError': 'Error syncing steps', 'health.todaySteps': "Today's steps", 'health.lastSync': 'Last sync', 'health.connectedProvider': 'Connected platform',
  'cal.delete': 'Delete', 'cal.confirmDelete': 'Delete workout', 'cal.confirmDeleteMsg': 'Are you sure you want to delete this workout? This action cannot be undone.', 'cal.deleted': 'Workout deleted', 'cal.deleting': 'Deleting...', 'cal.viewRoute': 'View route',
  'gps.summary': 'Route summary', 'gps.avgSpeed': 'Average speed', 'gps.maxSpeed': 'Max speed', 'gps.elevation': 'Elevation', 'gps.cadence': 'Cadence', 'gps.power': 'Estimated power', 'gps.pace': 'Average pace', 'gps.pacePerKm': 'min/km', 'gps.lapTime': 'Lap time', 'gps.stepCadence': 'Step cadence', 'gps.distance': 'Distance', 'gps.duration': 'Duration', 'gps.calories': 'Calories', 'gps.steps': 'Steps', 'gps.cyclingMetrics': 'Cycling metrics', 'gps.runningMetrics': 'Running metrics', 'gps.routeSummary': 'Activity summary', 'gps.finishActivity': 'Finish activity', 'gps.cyclingSummary': 'Cycling summary', 'gps.runningSummary': 'Running summary', 'gps.walkingSummary': 'Walking summary', 'gps.sportSummary': 'Activity summary',

};

const de: Dict = {
  'nav.home': 'Start', 'nav.summary': 'Zusammenfassung', 'nav.calendar': 'Kalender', 'nav.community': 'Community', 'nav.profile': 'Profil', 'nav.settings': 'Einstellungen', 'nav.record': 'Aufzeichnen',
  'dash.hello': 'Hallo', 'dash.today': 'Heute', 'dash.weekPlan': 'Wochenplan', 'dash.viewCalendar': 'Kalender ansehen', 'dash.regenerate': 'Gefällt mir nicht, erstell mir eine neue Woche', 'dash.generating': 'Wird erstellt...', 'dash.regenDone': 'Neuer Plan erstellt! Sieh in deinem Kalender nach.', 'dash.markDone': 'Als erledigt markieren', 'dash.doneToday': 'Heute erledigt!', 'dash.gps': 'GPS', 'dash.recordActivity': 'Aktivität aufzeichnen', 'dash.viewDetails': 'Details und Tipps ansehen', 'dash.recoveryDay': 'Aktiver Erholungstag', 'dash.restDay': 'Ruh dich aus und lade auf', 'dash.hydration': 'Hydration', 'dash.glasses': 'Gläser', 'dash.hydrationGoal': 'Hydrationsziel erreicht!', 'dash.yourGoal': 'Dein Ziel', 'dash.thisWeek': 'Diese Woche', 'dash.days': 'Tage', 'dash.workouts': 'Workouts', 'dash.weight': 'Gewicht', 'dash.progress': 'Fortschritt', 'dash.omsGoal': 'Tägliches WHO-Ziel erreicht!', 'dash.minutes': 'Min', 'dash.steps': 'Schritte', 'dash.calories': 'Kalorien', 'dash.omsMinutes': 'WHO-Minuten',
  'cal.title': 'Kalender', 'cal.weight': 'Gewicht', 'cal.weightEvolution': 'Gewichtsverlauf', 'cal.noWeight': 'Noch keine Gewichtsdaten.', 'cal.addFirst': 'Tippe auf "Gewicht" um deine erste Messung hinzuzufügen.', 'cal.firstRecord': 'Erster Eintrag. Füge mehr hinzu um den Verlauf zu sehen.', 'cal.weeklyPlan': 'Wochenplan', 'cal.tapDetails': 'Tippe für Details oder zum Ändern', 'cal.details': 'Details', 'cal.change': 'Ändern', 'cal.cancel': 'Abbrechen', 'cal.noWorkoutsDay': 'Keine Workouts an diesem Tag.', 'cal.recentHistory': 'Letzte Historie', 'cal.loading': 'Lädt...', 'cal.noWorkouts': 'Du hast noch keine Workouts aufgezeichnet.', 'cal.registerFirst': 'Zeichne dein erstes über den "Aufzeichnen"-Tab auf.', 'cal.shared': 'Geteilt', 'cal.public': 'Öffentlich', 'cal.private': 'Privat', 'cal.nutrition': 'Ernährung', 'cal.dailyCalories': 'Tägliche Kalorien', 'cal.protein': 'Protein', 'cal.carbs': 'Kohlenhydrate', 'cal.fat': 'Fett', 'cal.registerWeight': 'Gewicht eintragen', 'cal.weightInKg': 'Gewicht in kg', 'cal.saveWeight': 'Gewicht speichern', 'cal.vagonetaMsg': 'Na komm, willst du wirklich nichts tun, Faulpelz? 😄',
  'sum.title': 'Zusammenfassung', 'sum.congrats': 'Glückwunsch!', 'sum.weeklyProgress': 'Wöchentlicher WHO-Fortschritt', 'sum.today': 'Heute', 'sum.strengthDays': 'Krafttage', 'sum.dailyGoal': 'Tagesziel', 'sum.recommended': 'Empfohlen', 'sum.totalMinutes': 'Gesamtminuten', 'sum.km': 'Kilometer', 'sum.elevation': 'Höhenmeter (m)', 'sum.workouts': 'Workouts', 'sum.smartwatch': 'Smartwatch synchronisieren', 'sum.connectWatch': 'Verbinde deine Smartwatch um Daten automatisch zu übertragen', 'sum.connect': 'Verbinden', 'sum.softRest': 'Leichte Pause markieren', 'sum.softRestDesc': 'Erfasse einen aktiven Ruhetag ohne Druck', 'sum.achievements': 'Erfolge', 'sum.unlocked': 'Freigeschaltet', 'sum.sleepQuestion': 'Wie hast du geschlafen?', 'sum.sleepAdjust': 'Wir passen deinen Plan an deinen Schlaf an', 'sum.sleepGood': 'Gut', 'sum.sleepFair': 'Mittel', 'sum.sleepPoor': 'Schlecht', 'sum.sleepSuggestion': 'Wir haben bemerkt, dass du nicht gut geruht hast. Wir empfehlen, heute auf ein leichteres Workout zu wechseln (aktive Erholung oder Mobilität). Du kannst deinen Originalplan behalten wenn du möchtest.', 'sum.badWeather': 'Schlechtes Wetter. Versuch heute Indoor-Übungen!', 'sum.goodWeather': 'Gutes Wetter für Outdoor-Training', 'sum.indoor': 'Indoor', 'sum.omsWeekly': 'Wöchentliches WHO-Ziel erreicht!',
  'set.title': 'Einstellungen', 'set.currentPlan': 'Aktueller Plan', 'set.manageSub': 'Abonnement verwalten', 'set.sports': 'Sportarten', 'set.edit': 'Bearbeiten', 'set.close': 'Schließen', 'set.selectSports': 'Wähle die Sportarten die du ausübst. Du kannst jederzeit hinzufügen oder entfernen.', 'set.addCustom': 'Eigene Sportart hinzufügen...', 'set.saveSports': 'Sportarten speichern', 'set.saved': 'Gespeichert', 'set.saving': 'Speichert...', 'set.weeklyPlan': 'Wochenplan', 'set.regenerateDesc': 'Gefällt dir dein aktueller Plan nicht? Erstelle einen neuen mit deinen Sportarten und deinem Ziel.', 'set.notifications': 'Benachrichtigungen', 'set.notifGeneral': 'Allgemeine Benachrichtigungen', 'set.notifGeneralDesc': 'Alle Benachrichtigungen aktivieren oder deaktivieren', 'set.notifFriends': 'Freunde-Aktivität', 'set.notifFriendsDesc': 'Benachrichtigungen wenn Freunde trainieren oder Anfragen senden', 'set.notifChallenges': 'Herausforderungen', 'set.notifChallengesDesc': 'Benachrichtigungen über Herausforderungen, Ranglisten und Fristen', 'set.notifAchievements': 'Erfolge', 'set.notifAchievementsDesc': 'Benachrichtigungen wenn du einen neuen Erfolg oder Level freischaltest', 'set.units': 'Einheiten', 'set.weightUnit': 'Gewichtseinheit', 'set.kg': 'Kilogramm', 'set.lbs': 'Pfund', 'set.language': 'Sprache', 'set.account': 'Dein Konto', 'set.email': 'E-Mail', 'set.name': 'Name',
  'prof.title': 'Profil', 'prof.personalInfo': 'Persönliche Infos', 'prof.bodyStats': 'Körperdaten', 'prof.weight': 'Gewicht (kg)', 'prof.height': 'Größe (cm)', 'prof.age': 'Alter', 'prof.sex': 'Geschlecht', 'prof.male': 'Männlich', 'prof.female': 'Weiblich', 'prof.memberSince': 'Mitglied seit', 'prof.goal': 'Ziel', 'prof.sports': 'Sportarten', 'prof.nameUpdated': 'Name aktualisiert', 'prof.birthDate': 'Geburtsdatum', 'prof.happyBirthday': 'Alles Gute zum Geburtstag!', 'prof.birthdayMsg': 'Heute ist dein Geburtstag. Genieße deinen besonderen Tag und trainiere voller Energie!',
  'ex.sessionGoal': 'Sitzungsziel', 'ex.tips': 'Trainingstipps', 'ex.understood': 'Verstanden', 'ex.duration': 'Dauer', 'ex.calories': 'Kalorien', 'ex.intensity': 'Intensität', 'ex.low': 'Niedrig', 'ex.medium': 'Mittel', 'ex.high': 'Hoch', 'ex.notFeeling': 'Magst du diese Übung nicht?', 'ex.changeExercise': 'Übung ändern', 'ex.changing': 'Wird geändert...', 'ex.changed': 'Übung geändert!',
  'mat.title': 'Equipment', 'mat.desc': 'Konfiguriere welches Equipment du für Home-Workouts hast. Wir passen Empfehlungen an dein Material an.', 'mat.gym': 'Ich gehe ins Gym (alles verfügbar)', 'mat.gymDesc': 'Wenn du im Gym trainierst, musst du kein Equipment auswählen.', 'mat.home': 'Home-Workout', 'mat.homeDesc': 'Wähle das Equipment das du zu Hause hast.', 'mat.save': 'Equipment speichern', 'mat.saved': 'Equipment gespeichert', 'mat.saving': 'Speichert...', 'mat.dumbbells': 'Kurzhanteln', 'mat.barbell': 'Barbell und Scheiben', 'mat.kettlebell': 'Kettlebell', 'mat.bands': 'Widerstandsbänder', 'mat.pullup': 'Klimmzugstange', 'mat.bench': 'Bank', 'mat.mat': 'Matte', 'mat.bodyweight': 'Nur Körpergewicht',
  'common.cancel': 'Abbrechen', 'common.save': 'Speichern',
  'goal.lose_weight': 'Gewicht verlieren', 'goal.gain_muscle': 'Muskelaufbau', 'goal.general_health': 'Sport für die Gesundheit', 'goal.define': 'Definition', 'goal.gain_strength': 'Kraft gewinnen',
  'set.changeGoal': 'Ziel ändern', 'set.changeGoalDesc': 'Ändere dein Hauptziel. Dein Plan und Empfehlungen werden angepasst.', 'set.goalChanged': 'Ziel aktualisiert! Dein Plan wurde neu erstellt.',
  'health.title': 'Gesundheits-App-Verbindung', 'health.desc': 'Verbinde dich mit der Gesundheitsplattform deines Geräts um deine täglichen Schritte automatisch zu synchronisieren.', 'health.connect': 'Verbinden', 'health.disconnect': 'Trennen', 'health.connected': 'Verbunden', 'health.disconnected': 'Nicht verbunden', 'health.connecting': 'Verbinden...', 'health.selectProvider': 'Wähle deine Gesundheitsplattform', 'health.appleHealth': 'Apple Health', 'health.googleFit': 'Google Fit', 'health.healthConnect': 'Health Connect', 'health.samsungHealth': 'Samsung Health', 'health.huaweiHealth': 'Huawei Health', 'health.permissionTitle': 'Gesundheitsberechtigungen', 'health.permissionDesc': 'Wir benötigen Berechtigung um deine täglichen Schritte von der Gesundheitsplattform deines Geräts zu lesen.', 'health.requestPermission': 'Berechtigung anfordern', 'health.grant': 'Zugriff gewähren', 'health.infoNote': 'Hinweis: Beim Verbinden werden nur tägliche Schritte automatisch synchronisiert und hochgeladen. Importierte Schritte zählen nicht als abgeschlossene Trainingseinheit (sie werden nicht als 45 Minuten geplante Aktivität gezählt).', 'health.synced': 'Schritte erfolgreich synchronisiert', 'health.syncError': 'Fehler beim Synchronisieren der Schritte', 'health.todaySteps': 'Schritte heute', 'health.lastSync': 'Letzte Synchronisierung', 'health.connectedProvider': 'Verbundene Plattform',
  'cal.delete': 'Löschen', 'cal.confirmDelete': 'Workout löschen', 'cal.confirmDeleteMsg': 'Möchtest du dieses Workout wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.', 'cal.deleted': 'Workout gelöscht', 'cal.deleting': 'Löschen...', 'cal.viewRoute': 'Route ansehen',
  'gps.summary': 'Routenzusammenfassung', 'gps.avgSpeed': 'Durchschnittsgeschwindigkeit', 'gps.maxSpeed': 'Max. Geschwindigkeit', 'gps.elevation': 'Höhenmeter', 'gps.cadence': 'Kadenz', 'gps.power': 'Geschätzte Leistung', 'gps.pace': 'Durchschnittstempo', 'gps.pacePerKm': 'min/km', 'gps.lapTime': 'Rundenzeit', 'gps.stepCadence': 'Schrittkadenz', 'gps.distance': 'Distanz', 'gps.duration': 'Dauer', 'gps.calories': 'Kalorien', 'gps.steps': 'Schritte', 'gps.cyclingMetrics': 'Radsport-Metriken', 'gps.runningMetrics': 'Lauf-Metriken', 'gps.routeSummary': 'Aktivitätszusammenfassung', 'gps.finishActivity': 'Aktivität beenden', 'gps.cyclingSummary': 'Radsport-Zusammenfassung', 'gps.runningSummary': 'Lauf-Zusammenfassung', 'gps.walkingSummary': 'Geh-Zusammenfassung', 'gps.sportSummary': 'Aktivitätszusammenfassung',

};

const zh: Dict = {
  'nav.home': '首页', 'nav.summary': '总结', 'nav.calendar': '日历', 'nav.community': '社区', 'nav.profile': '个人资料', 'nav.settings': '设置', 'nav.record': '记录',
  'dash.hello': '你好', 'dash.today': '今天', 'dash.weekPlan': '本周计划', 'dash.viewCalendar': '查看日历', 'dash.regenerate': '不喜欢，给我重新安排一周', 'dash.generating': '生成中...', 'dash.regenDone': '新计划已生成！请查看日历。', 'dash.markDone': '标记完成', 'dash.doneToday': '今日已完成！', 'dash.gps': 'GPS', 'dash.recordActivity': '记录活动', 'dash.viewDetails': '查看详情和建议', 'dash.recoveryDay': '主动恢复日', 'dash.restDay': '休息并充电', 'dash.hydration': '补水', 'dash.glasses': '杯', 'dash.hydrationGoal': '已达到补水目标！', 'dash.yourGoal': '你的目标', 'dash.thisWeek': '本周', 'dash.days': '天', 'dash.workouts': '训练', 'dash.weight': '体重', 'dash.progress': '进度', 'dash.omsGoal': '已达到每日WHO目标！', 'dash.minutes': '分钟', 'dash.steps': '步数', 'dash.calories': '卡路里', 'dash.omsMinutes': 'WHO分钟',
  'cal.title': '日历', 'cal.weight': '体重', 'cal.weightEvolution': '体重变化', 'cal.noWeight': '暂无体重记录。', 'cal.addFirst': '点击"体重"添加你的第一次测量。', 'cal.firstRecord': '第一条记录。添加更多以查看变化趋势。', 'cal.weeklyPlan': '周计划', 'cal.tapDetails': '点击查看详情或更改', 'cal.details': '详情', 'cal.change': '更改', 'cal.cancel': '取消', 'cal.noWorkoutsDay': '今天没有训练。', 'cal.recentHistory': '最近记录', 'cal.loading': '加载中...', 'cal.noWorkouts': '你还没有记录任何训练。', 'cal.registerFirst': '从"记录"标签页记录你的第一次训练。', 'cal.shared': '已分享', 'cal.public': '公开', 'cal.private': '私密', 'cal.nutrition': '营养', 'cal.dailyCalories': '每日卡路里', 'cal.protein': '蛋白质', 'cal.carbs': '碳水', 'cal.fat': '脂肪', 'cal.registerWeight': '记录体重', 'cal.weightInKg': '体重（公斤）', 'cal.saveWeight': '保存体重', 'cal.vagonetaMsg': '来吧，你什么都不想做吗，懒虫？😄',
  'sum.title': '总结', 'sum.congrats': '恭喜！', 'sum.weeklyProgress': '每周WHO进度', 'sum.today': '今天', 'sum.strengthDays': '力量训练日', 'sum.dailyGoal': '每日目标', 'sum.recommended': '推荐', 'sum.totalMinutes': '总分钟数', 'sum.km': '公里', 'sum.elevation': '爬升（米）', 'sum.workouts': '训练', 'sum.smartwatch': '同步智能手表', 'sum.connectWatch': '连接你的智能手表以自动同步数据', 'sum.connect': '连接', 'sum.softRest': '标记轻度休息', 'sum.softRestDesc': '记录一个无压力的主动休息日', 'sum.achievements': '成就', 'sum.unlocked': '已解锁', 'sum.sleepQuestion': '你睡得怎么样？', 'sum.sleepAdjust': '我们根据你的休息调整计划', 'sum.sleepGood': '好', 'sum.sleepFair': '一般', 'sum.sleepPoor': '差', 'sum.sleepSuggestion': '我们注意到你没有休息好。建议今天换成更轻的训练（主动恢复或灵活性训练）。如果你愿意可以保留原计划。', 'sum.badWeather': '天气不好。今天试试室内运动吧！', 'sum.goodWeather': '天气适合户外训练', 'sum.indoor': '室内', 'sum.omsWeekly': '已达到每周WHO目标！',
  'set.title': '设置', 'set.currentPlan': '当前计划', 'set.manageSub': '管理订阅', 'set.sports': '运动', 'set.edit': '编辑', 'set.close': '关闭', 'set.selectSports': '选择你从事的运动。可以随时添加或删除。', 'set.addCustom': '添加自定义运动...', 'set.saveSports': '保存运动', 'set.saved': '已保存', 'set.saving': '保存中...', 'set.weeklyPlan': '周计划', 'set.regenerateDesc': '不喜欢当前计划？根据你的运动和目标生成新的。', 'set.notifications': '通知', 'set.notifGeneral': '通用通知', 'set.notifGeneralDesc': '开启或关闭所有通知', 'set.notifFriends': '好友活动', 'set.notifFriendsDesc': '好友训练或发送请求时的提醒', 'set.notifChallenges': '挑战', 'set.notifChallengesDesc': '关于挑战、排名和截止日期的提醒', 'set.notifAchievements': '成就', 'set.notifAchievementsDesc': '解锁新成就或等级时的提醒', 'set.units': '单位', 'set.weightUnit': '体重单位', 'set.kg': '公斤', 'set.lbs': '磅', 'set.language': '语言', 'set.account': '你的账户', 'set.email': '邮箱', 'set.name': '姓名',
  'prof.title': '个人资料', 'prof.personalInfo': '个人信息', 'prof.bodyStats': '身体数据', 'prof.weight': '体重（公斤）', 'prof.height': '身高（厘米）', 'prof.age': '年龄', 'prof.sex': '性别', 'prof.male': '男', 'prof.female': '女', 'prof.memberSince': '注册时间', 'prof.goal': '目标', 'prof.sports': '运动', 'prof.nameUpdated': '姓名已更新', 'prof.birthDate': '出生日期', 'prof.happyBirthday': '生日快乐！', 'prof.birthdayMsg': '今天是你的生日。享受你的特别日子，充满能量地训练吧！',
  'ex.sessionGoal': '训练目标', 'ex.tips': '训练建议', 'ex.understood': '明白了', 'ex.duration': '时长', 'ex.calories': '卡路里', 'ex.intensity': '强度', 'ex.low': '低', 'ex.medium': '中', 'ex.high': '高', 'ex.notFeeling': '不喜欢这个练习？', 'ex.changeExercise': '更换练习', 'ex.changing': '更换中...', 'ex.changed': '练习已更换！',
  'mat.title': '器材', 'mat.desc': '配置你在家训练可用的器材。我们会根据你的器材调整建议。', 'mat.gym': '我去健身房（全部可用）', 'mat.gymDesc': '如果你在健身房训练，不需要选择器材。', 'mat.home': '在家训练', 'mat.homeDesc': '选择你在家可用的器材。', 'mat.save': '保存器材', 'mat.saved': '器材已保存', 'mat.saving': '保存中...', 'mat.dumbbells': '哑铃', 'mat.barbell': '杠铃和杠铃片', 'mat.kettlebell': '壶铃', 'mat.bands': '弹力带', 'mat.pullup': '引体向上杆', 'mat.bench': '长凳', 'mat.mat': '垫子', 'mat.bodyweight': '仅自重',
  'common.cancel': '取消', 'common.save': '保存',
  'goal.lose_weight': '减重', 'goal.gain_muscle': '增肌', 'goal.general_health': '为健康运动', 'goal.define': '塑形', 'goal.gain_strength': '增力',
  'set.changeGoal': '更改目标', 'set.changeGoalDesc': '更改你的主要目标。你的计划和建议将自动调整。', 'set.goalChanged': '目标已更新！你的计划已重新生成。',
  'health.title': '健康应用连接', 'health.desc': '连接你设备的健康平台以自动同步每日步数。', 'health.connect': '连接', 'health.disconnect': '断开', 'health.connected': '已连接', 'health.disconnected': '未连接', 'health.connecting': '连接中...', 'health.selectProvider': '选择你的健康平台', 'health.appleHealth': 'Apple Health', 'health.googleFit': 'Google Fit', 'health.healthConnect': 'Health Connect', 'health.samsungHealth': '三星健康', 'health.huaweiHealth': '华为健康', 'health.permissionTitle': '健康权限', 'health.permissionDesc': '我们需要权限来从你设备的健康平台读取每日步数。', 'health.requestPermission': '请求权限', 'health.grant': '授予访问权限', 'health.infoNote': '注意：连接后，仅会自动同步和上传每日步数。导入的步数不会算作已完成的训练（不会计为45分钟的计划活动）。', 'health.synced': '步数同步成功', 'health.syncError': '同步步数时出错', 'health.todaySteps': '今日步数', 'health.lastSync': '上次同步', 'health.connectedProvider': '已连接平台',
  'cal.delete': '删除', 'cal.confirmDelete': '删除训练', 'cal.confirmDeleteMsg': '确定要删除此训练吗？此操作无法撤销。', 'cal.deleted': '训练已删除', 'cal.deleting': '删除中...', 'cal.viewRoute': '查看路线',
  'gps.summary': '路线总结', 'gps.avgSpeed': '平均速度', 'gps.maxSpeed': '最大速度', 'gps.elevation': '爬升', 'gps.cadence': '踏频', 'gps.power': '估算功率', 'gps.pace': '平均配速', 'gps.pacePerKm': '分钟/公里', 'gps.lapTime': '圈速', 'gps.stepCadence': '步频', 'gps.distance': '距离', 'gps.duration': '时长', 'gps.calories': '卡路里', 'gps.steps': '步数', 'gps.cyclingMetrics': '骑行指标', 'gps.runningMetrics': '跑步指标', 'gps.routeSummary': '活动总结', 'gps.finishActivity': '结束活动', 'gps.cyclingSummary': '骑行总结', 'gps.runningSummary': '跑步总结', 'gps.walkingSummary': '步行总结', 'gps.sportSummary': '活动总结',

};

export const DICTS: Record<Lang, Dict> = { es, eu, en, de, zh };
